name: CI for Docker 
description: "CI workflow for building and pushing Docker images"

inputs:
  docker-username:
    description: 'Docker Hub username'
    required: true
  docker-password:
    description: 'Docker Hub password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build Stage
      run: docker compose build
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Push Stage
      run: docker compose push 
      shell: bash